name = "quality-platform-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "quality-platform-db"
database_id = "1cdb01dd-fd67-4843-bbb2-eadbb70ea733"

[vars]
ENVIRONMENT = "development"
APP_NAME = "Quality Platform API"

# Variáveis de ambiente sensíveis — configurar via: wrangler secret put JWT_SECRET
# JWT_SECRET     = ""
# RESEND_API_KEY = ""

[env.production]
name = "quality-platform-api-prod"
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "quality-platform-db"
database_id = "1cdb01dd-fd67-4843-bbb2-eadbb70ea733"